const String _base = 'lib/ecliniq_icons/assets';
const String _base1 = 'lib/ecliniq_icons/assets/specs';

enum EcliniqIcons {
  ayurvedic('$_base1/ayurvedic.png'),
  homeopathy('$_base1/homeopathy .png'),
  haematologist('$_base1/Haematologist.png'),
  radiologist('$_base1/Radiologist.png'),
  endocrinologist('$_base1/Endocrinologist.png'),
  hepatologist('$_base1/Hepatologists.png'),
  sexologist('$_base1/Sexologist.png'),
  neurologist('$_base1/Neurologist.png'),
  oncologist('$_base1/Oncologist.png'),
  urologist('$_base1/Urologist.png'),
  physiotherapist('$_base1/Physiotherapist.png'),
  psychiatrist('$_base1/Psychiatrist:Psychologist: Counsellor.png'),
  gastroenterologist('$_base1/Gastroenterologist.png'),
  nephrologist('$_base1/Nephrologist.png'),
  pulmonologist('$_base1/Pulmonologist.png'),
  diabetologist('$_base1/Diabetologist.png'),
  orthopedic('$_base1/Orthopedic.png'),
  cardiologist('$_base1/Cardiologist.png'),
  ophthalmologist('$_base1/Ophthalmologist.png'),
  ent('$_base1/ENT.png'),
  dermatologist('$_base1/Dermatologist.png'),
  dentist('$_base1/Dentist.png'),
  pediatrician('$_base1/Pediatrician.png'),
  generalPhysician('$_base1/General Physician.png'),
  gynaecologist('$_base1/Gynaecologist.png'),
  nofiles('$_base/no_files.svg'),
  arrowBack('$_base/back_arrow.png'),
  main('$_base/main.png'),
  mpin('$_base/Group (1).png'),
  shield('$_base/shield.png'),
  appointment('$_base/AppointmentRemindar.png'),
  library('$_base/Library.png'),
  userCircle('$_base/User Circle.png'),
  home('$_base/Home.png'),
  nameLogo('$_base/Frame1 2.svg'),
  quick1('$_base/Sthethoscope.svg'),
  coinLarge('$_base/CoinLarge.svg'),
  upcharCoin('$_base/5 - Logos aplicado.png'),
  upcharCoinSmall('$_base/5 - Logos aplicado (1).svg'),
  upcharCoinSmall1('$_base/coinsmall.png'),
  googlePay('$_base/gpay.png'),
  bhimPay('$_base/bhim.png'),
  phonePe('$_base/phonepe.png'),
  card('$_base/Card.svg'),
  cred('$_base/cred.png'),
  bell('$_base/Bell.png'),
  arrowUp('$_base/Angle Up.svg'),
  microphone('$_base/Microphone.svg'),
  hospitalorange('$_base/HospitalOrange.svg'),
  verify('$_base/Verified Check.png'),
  lottie('$_base/lottie.gif'),
  appointment1('$_base/Group 56824.svg'),
  appointment2('$_base/Group (5).svg'),
  phone('$_base/phone.svg'),
  red('$_base/red_frame_new.svg'),
  blue('$_base/blue_card.svg'),
  verified('$_base/verified.svg'),
  blueGradient('$_base/blue_grad.svg'),
  green('$_base/green.svg'),
  orange('$_base/orange.svg'),
  yellow('$_base/yellow.svg'),
  blueDark('$_base/blue_dark.svg'),
  yellowframe('$_base/yellow_frame.svg'),
  blueDarkframe('$_base/dark_blue_frame.svg'),
  greenframe('$_base/green_frame.svg'),
  orangeframe('$_base/orange_frame.svg'),
  redframe('$_base/red_frame.svg'),
  prescription('$_base/prescription.png'),
  threeDots('$_base/MenuDots.svg'),
  thankYou('$_base/a9d6a497adb19616261681e54fbc5335cbabafdd.gif'),
  star('$_base/StarRating.svg'),
  starRateExp('$_base/StarFilledRateExp.svg'),
  starRateExpUnfilled('$_base/StarUnfilled.svg'),
  stethoscope('$_base/Stethoscope.svg'),
  userCircle1('$_base/user_circle.svg'),
  lockKeyHoleMinimalistic('$_base/lock_key_hole_minimalistic.svg'),
  medicalKit('$_base/Medical Kit.svg'),
  heart('$_base/Heart.svg'),
  appointmentRemindar('$_base/Appointment Remindar.svg'),
  verifiedCheck('$_base/Verified Check.svg'),
  map('$_base/Map Point.svg'),
  errorIcon('$_base/error_snackbar.svg'),
  actionIcon('$_base/action_snackbar.svg'),
  microphoneMyDoctor('$_base/Action Button (2).svg'),
  magnifierMyDoctor('$_base/Magnifer.svg'),
  userHeartRounded('$_base/User Heart Rounded.svg'),
  pointOnMap('$_base/Point On Map.svg'),
  mapPointBlack('$_base/Map Point Black.svg'),
  dropperMinimalistic('$_base/Dropper Minimalistic.svg'),
  gender('$_base/gender_sign.svg'),
  refreshed('$_base/Refresh.svg'),
  add('$_base/Add.svg'),
  arrowLeft('$_base/Arrow Left.svg'),
  questionCircle('$_base/Question Circle.svg'),
  questionMark('$_base/Question Circle White.svg'),
  verifiedGreen('$_base/Verified Check Green.svg'),
  bellBlue('$_base/Bell Blue.svg'),
  ecliniqLogo('$_base/Frame1 2.svg'),
  sort('$_base/Sort.svg'),
  chatMessage('$_base/Chat Group.svg'),
  smartphone('$_base/Smartphone.svg'),
  stethoscope2('$_base/StethoscopeFilled.svg'),
  whatsapp('$_base/whatsapp (1).svg'),
  clipboard('$_base/Clipboard.svg'),
  copy('$_base/Copy.svg'),
  infoCircle('$_base/Info Circle.svg'),
  like('$_base/Like.svg'),
  logout('$_base/Logout.svg'),
  mail('$_base/Mail.svg'),
  restart('$_base/Restart.svg'),
  share('$_base/Share.svg'),
  shieldStar('$_base/Shield Star.svg'),
  sms('$_base/SMS.svg'),
  taskType('$_base/Task Type.svg'),
  password('$_base/Password.svg'),
  faceScanSquare('$_base/Face Scan Square.svg'),
  angleRight('$_base/Angle Right.svg'),
  angleDown('$_base/Angle Down.svg'),
  trashBin2('$_base/Trash Bin 2.svg'),
  clockCircle('$_base/Clock Circle.svg'),
  arrowRightWhite('$_base/Arrow Right.svg'),
  arrowRight1('$_base/arrow_right.svg'),
  caseDoctor('$_base/Case.svg'),
  mailBlue('$_base/MailBlue.svg'),
  mapArrow('$_base/Map Arrow.svg'),
  userSpeak('$_base/User Speak.svg'),
  academicCap('$_base/Square Academic Cap.svg'),
  heartUnfilled('$_base/heartUnfilled.svg'),
  stars('$_base/Stars.svg'),
  tagPrice('$_base/Tag Price.svg'),
  usersGroupRounded('$_base/Users Group Rounded.svg'),
  medicalKit1('$_base/Medical Kit.svg'),
  shuffle('$_base/Shuffle.svg'),
  mapPoint('$_base/Map Point.svg'),
  hospitalBuilding1('$_base/Office.svg'),
  checkWhite('$_base/check white.svg'),
  afternoon('$_base/Sun.svg'),
  morning('$_base/Sunrise.svg'),
  evening('$_base/Sunset.svg'),
  night('$_base/Moon Sleep.svg'),
  editIcon('$_base/Action Button.svg'),
  calendar('$_base/Calendar Minimalistic.svg'),
  user('$_base/User.svg'),
  arrowDown('$_base/Angle Down.svg'),
  backArrow('$_base/back_arrow.svg'),
  healthfile('$_base/health_files.svg'),
  myVisits('$_base/my_visits.svg'),
  explore('$_base/explore.svg'),
  healthIcon('$_base/files_health.svg'),
  camera('$_base/Camera.svg'),
  fileSend('$_base/File Send.svg'),
  gallery('$_base/Gallery Set.svg'),
  download('$_base/Download Square.svg'),
  penEdit('$_base/Pen.svg'),
  delete('$_base/Trash Bin 2.svg'),
  arrowRight('$_base/Arrow Right.svg'),
  snackbar('$_base/Frame 5.svg'),
  profile('$_base/UserProfile.svg'),
  calendar1('$_base/Calendar.svg'),
  bed('$_base/Bed.svg'),
  starHistory('$_base/StarDoctorhistory.svg'),
  sthes('$_base/Stethoscope.svg'),
  abhaId('$_base/abha_logo.svg'),
  call('$_base/Incoming Call.svg'),
  appointmentReminder('$_base/Appointment Remindar.svg'),
  info('$_base/Info Circle.svg'),
  greenDot('$_base/Ellipse 310.svg'),
  filter('$_base/Filter.svg'),
  cancelGif('$_base/cancel.svg'),
  notification('$_base/d0ad8332280e0f971172b36a4ad1cf732e72d70c.gif'),
  notifilter('$_base/filter_notif.svg'),
  doubleMark('$_base/Check Read.svg'),
  rescheduleIcon('$_base/Calendar Reschedule.svg'),
  rescheduleCancel('$_base/Calendar X.svg'),
  reschedule('$_base/reschedule.svg'),
  shieldCheck('$_base/Shield Check.svg'),
  eyeOpen('$_base/Eye.svg'),
  eyeClosed('$_base/Eye Closed.svg'),
  faceId('$_base/Face Scan Square.svg'),
  notificationBell('$_base/Bell.svg'),
  hospitalBuilding('$_base/Hospital_1.svg'),
  deleteFile('$_base/Clip path group.svg'),
  doctorDefault('$_base/doctor_default.svg'),
  callEmergency('$_base/Call Emergency.svg'),
  drop('$_base/Drop.svg'),
  mapPointBlue('$_base/Map Point Blue.svg'),
  certificate('$_base/Medal Ribbon Star.svg'),
  sirenRounded('$_base/Siren Rounded.svg'),
  stethoscopeBlue('$_base/StethoscopeBlue.svg'),
  scissors('$_base/Scissors.svg'),
  requestedIcon('$_base/Diploma Verified.svg'),
  progressIndicator('$_base/progress_indicator.svg'),
  sortAlt('$_base/Frame 3 (6).svg'),
  arrowRightBlue('$_base/Dropdown.svg'),
  locationSheet('$_base/location_sheet.svg'),
  noDoctor('$_base/no_doctor.svg'),
  noHospital('$_base/no_hospital.svg'),
  calendarCheck('$_base/Calendar Checked.svg'),
  bookingReceived('$_base/Plane.svg'),
  verifiedCheckGreen('$_base/ verified_green.svg'),
  questionCircleWhite('$_base/Question Circle Unfilled.svg'),
  calendarDate('$_base/calendar_date.svg'),
  men('$_base/Men.svg'),
  women('$_base/Women.svg'),
  genderTrans('$_base/Gender.svg'),
  questionCircleFilled('$_base/Question Circle Black.svg'),
  close('$_base/Close.svg'),
  checkRounded('$_base/Check Round.svg'),
  myVisitsFilled('$_base/Appointment RemindarSelected.svg'),
  homeFilled('$_base/HomeFilled.svg'),
  filesFilled('$_base/LibrarySelected.svg'),
  userSelected('$_base/UserSelected.svg'),
  arrowRightCoin('$_base/Angle Right Coin.svg'),
  shieldBlue('$_base/Shield Star Blue.svg'),
  closeCircle('$_base/Close Circle.svg'),
  deselect('$_base/Deselect.svg'),
  downloadfiles('$_base/Download.svg'),
  downloadDisabled('$_base/DownloadDisables.svg'),
  select('$_base/Select.svg'),
  trashBin('$_base/Trash Bin 2 Black.svg'),
  vectorTicked('$_base/VectorTick.svg'),
  minus('$_base/minus.svg'),
  pdffile('$_base/PDF.png'),
  upload('$_base/Upload Square.svg'),
  phoneBlue('$_base/Phone Calling.svg'),
  verifiedGreenDoctor('$_base/Verified Check Doctor.svg'),
  homeLogo('$_base/homepic.svg'),
  termsConditions('$_base/termscondition.png'),
  reply('$_base/Reply.svg'),
  userBlue('$_base/UserBlueApp.svg'),
  clockCircleHospital('$_base/Clock Circle Hospital.svg'),
  mapPointHospital('$_base/Map Point Hospital.svg'),
  photo1('$_base/photo1.svg'),
  photo2('$_base/photo2.svg'),
  photo3('$_base/photo3.svg'),
  photo4('$_base/photo4.svg'),
  photo5('$_base/photo5.svg'),
  photo6('$_base/photo6.svg'),
  photo7('$_base/photo7.svg'),
  penBlack('$_base/PenBlack.svg'),
  infoCircleBlack('$_base/Info Circle Black.svg'),
  splashScreenLogo('$_base/splash_screen.png'),
  visa('$_base/Visa.png'),
  bannerRequested('$_base/banner_requested.gif'),
  bannerConfirmed('$_base/banner_confirmed.svg'),
  history('$_base/History.svg'),
  sleepProblem('$_base/Sleep Problem 1.svg'),
  periodsProblem('$_base/Periods Problem 1.svg'),
  itchingOrSkinProblem('$_base/Iching or skin Problem 1.svg'),
  breathingProblem('$_base/Breathing Problem 1.svg'),
  backPain('$_base/Back Pain.svg'),
  bodyPain('$_base/Body Pain.svg'),
  coughCold('$_base/Cough Cold.svg'),
  stomachPain('$_base/Stomach pain 1.svg'),
  headache('$_base/Headache 1.svg'),
  fever('$_base/Fever 1.svg'),
  noSchedule('$_base/no_schedule.svg'),
  one('$_base/one.svg'),
  two('$_base/two.svg'),
  three('$_base/three.svg'),
  four('$_base/four.svg'),
  mapfilled('$_base/Map Point Filled.svg'),
  five('$_base/five.svg'),
  six('$_base/six.svg'),
  seven('$_base/seven.svg'),
  loginLogo('$_base/UpcharQ_horizontal 1.svg'),
  bloodPressure('$_base/Blood Pressure.svg'),
  dentalCare('$_base/Dental Care.svg'),
  hairCare('$_base/Hair Fall.svg'),
  jointCare('$_base/Joint pain.svg'),
  pregnancyCare('$_base/Pregency.svg'),
  deleteImage('$_base/Clip path group.png'),
  aboutLogo('$_base/Layer_x0020_1.png'),
  logoutImage('$_base/Group (4).png'),
  profileLogo('$_base/UpcharQ_horizontal 1.png'),
  noNotifications('$_base/no_notif.svg');

  

  final String assetPath;
  const EcliniqIcons(this.assetPath);
}
